import type { AxiProgressState, CrashInputs, OpportunityCandidate } from "./v72PerformanceEngine";

export const PAPER_BASELINE_AXI: AxiProgressState = {
  stage: "PRE_SEED",
  allocationStartBalance: 25_000,
  allocationEquity: 25_184.6,
  accountEquityUsd: 25_184.6,
  edgeScore: 72,
  closedTrades: 24,
  stageDays: 42,
  monthStartEquity: 24_700,
  currentEquity: 25_184.6,
  peakMonthlyProfitPct: 1.96,
};

export const PAPER_BASELINE_CRASH: CrashInputs = {
  vixZ: 0.8,
  realizedVolZ: 0.45,
  creditSpreadZ: 0.3,
  breadthPct: 52,
  crossAssetCorrelation: 0.35,
  liquidityStress: 32,
  spreadShockMultiple: 1.2,
  safeHavenConfirmation: 42,
  geopoliticalSeverity: 18,
};

const commonStatisticalInput = {
  correlation: 0.52,
  historicalCorrelation: 0.48,
  zScore: 1.7,
  cointegrationPValue: 0.08,
  leadLagStrength: 64,
  breadthConfirmation: 68,
  volatilityRatio: 1.25,
  directionalBias: "BULLISH" as const,
};

export const PAPER_OPPORTUNITY_CANDIDATES: OpportunityCandidate[] = [
  {
    symbol: "AAPL",
    expectedReturnR: 1.35,
    expectedRiskR: 0.72,
    confidence: 82,
    liquidityScore: 92,
    executionCostR: 0.04,
    portfolioCorrelation: 0.32,
    sectorConcentrationPct: 18,
    masterInput: {
      horizon: "swing",
      technical: { score: 81, confidence: 84 },
      macroNews: { score: 72, confidence: 70 },
      fundamentals: { price: 189.84, epsTtm: 6.42, epsForward: 7.12, expectedEpsGrowthPct: 11, revenueGrowthPct: 8.2, operatingMarginPct: 30.8, roePct: 156, debtToEquity: 1.79, sectorPeMedian: 28 },
      statistical: commonStatisticalInput,
      safety: { dataHealth: "OK", brokerConnected: true, riskScore: 32, volatilityShockMultiple: 1.1, spreadMultiple: 1.1, slippageMultiple: 1.05 },
    },
  },
  {
    symbol: "MSFT",
    expectedReturnR: 1.52,
    expectedRiskR: 0.68,
    confidence: 86,
    liquidityScore: 94,
    executionCostR: 0.035,
    portfolioCorrelation: 0.28,
    sectorConcentrationPct: 16,
    masterInput: {
      horizon: "position",
      technical: { score: 84, confidence: 86 },
      macroNews: { score: 76, confidence: 74 },
      fundamentals: { price: 417.32, epsTtm: 11.8, epsForward: 13.2, expectedEpsGrowthPct: 14, revenueGrowthPct: 15.2, operatingMarginPct: 44.6, roePct: 35.8, debtToEquity: 0.42, sectorPeMedian: 28 },
      statistical: { ...commonStatisticalInput, correlation: 0.58, breadthConfirmation: 74 },
      safety: { dataHealth: "OK", brokerConnected: true, riskScore: 29, volatilityShockMultiple: 1.05, spreadMultiple: 1.05, slippageMultiple: 1.02 },
    },
  },
  {
    symbol: "EUR/USD",
    expectedReturnR: 0.88,
    expectedRiskR: 0.82,
    confidence: 70,
    liquidityScore: 88,
    executionCostR: 0.06,
    portfolioCorrelation: 0.12,
    sectorConcentrationPct: 8,
    masterInput: {
      horizon: "intraday",
      technical: { score: 74, confidence: 78 },
      macroNews: { score: 58, confidence: 64 },
      statistical: { ...commonStatisticalInput, zScore: 1.2, directionalBias: "NEUTRAL" },
      safety: { dataHealth: "OK", brokerConnected: true, riskScore: 41, volatilityShockMultiple: 1.4, spreadMultiple: 1.25, slippageMultiple: 1.15 },
    },
  },
  {
    symbol: "XAU/USD",
    expectedReturnR: 0.92,
    expectedRiskR: 1.02,
    confidence: 66,
    liquidityScore: 78,
    executionCostR: 0.1,
    portfolioCorrelation: 0.44,
    sectorConcentrationPct: 12,
    masterInput: {
      horizon: "swing",
      technical: { score: 63, confidence: 70 },
      macroNews: { score: 76, confidence: 78 },
      statistical: { ...commonStatisticalInput, correlation: 0.34, zScore: 1.4, directionalBias: "BULLISH" },
      safety: { dataHealth: "DEGRADED", brokerConnected: true, riskScore: 54, volatilityShockMultiple: 1.9, spreadMultiple: 1.6, slippageMultiple: 1.4 },
    },
  },
  {
    symbol: "NAS100",
    expectedReturnR: 0.6,
    expectedRiskR: 1.15,
    confidence: 54,
    liquidityScore: 84,
    executionCostR: 0.08,
    portfolioCorrelation: 0.91,
    sectorConcentrationPct: 42,
    masterInput: {
      horizon: "swing",
      technical: { score: 55, confidence: 62 },
      macroNews: { score: 48, confidence: 60 },
      statistical: { ...commonStatisticalInput, correlationBreakdown: true, directionalBias: "NEUTRAL" },
      safety: { dataHealth: "OK", brokerConnected: true, riskScore: 68, volatilityShockMultiple: 2.2, spreadMultiple: 1.8, slippageMultiple: 1.7 },
    },
  },
];